### ISSUE TITLE
build error: except TradeFailedException not found

### ISSUE THREAD

**Issue by gclsoft** [littlekfc/threebody#2]
```
  File "/Users/apple/node/undo4096/tool/videoPei/btc/threebody-master/threebody.py", line 356
    except TradeFailedException, e:
                               ^
SyntaxError: invalid syntax
```

**Comment by littlekfc** [comment]
It shouldn't have grammar error.  I have written simple 'How to Use'. You can follow it. You needn't to change the code except config files.

**Comment by xiaosworld** [comment]
Excuse me, where can I find the ltc_withdraw_addr, btc_withdraw_addr, src_fid, dst_fid and private_key? Or I don't need them at all?
